<?php

namespace AppBundle\Repository;

/**
 * StoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllStores(){
        $dql = $this->createQueryBuilder('s')
            ->select('s.name','s.image','s.description')
        ;
        $query = $dql->getQuery();

        return $query->execute();
    }


}
