<?php

namespace AppBundle\Repository;

/**
 * UserStoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserStoreRepository extends \Doctrine\ORM\EntityRepository
{
}
