<?php

namespace AppBundle\Repository;

/**
 * UserStoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserStoreRepository extends \Doctrine\ORM\EntityRepository
{
    public function findStoresLiked($user){
        $dql = $this->createQueryBuilder('us')
            ->innerJoin('us.store', 'st')
            ->select('us.id','us.rate','st.id')
            ->where('us.rate = 1')
            ->andWhere('us.user = :user')
            ->setParameter('user', $user)
        ;
        $query = $dql->getQuery();

        return $query->execute();
    }
}
